version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: keycloak_postgres_kc_lern
    environment:

    ports:
      - "5447:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    container_name: keycloak
    environment:

    ports:
      - "8088:8080"
    depends_on:
      - postgres
    networks:
      - keycloak-network
    command: start-dev

volumes:
  postgres_data:

networks:
  keycloak-network:
